=== Naijing/JinJin-Music-App/playlist.dtd
<!ELEMENT playlist (item+)>
<!ELEMENT item (image,track,artiste,album,annee,preview)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT track (#PCDATA)>
<!ELEMENT artiste (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT preview (#PCDATA)>

=== Naijing/JinJin-Music-App/playlist.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE playlist SYSTEM "playlist.dtd">
<playlist><item><image>https://i.scdn.co/image/7d7b78e1624f85311a6424296eb8dfce0cbb81c2</image><track>Love Song</track><artiste>方大同</artiste><album>未來</album><annee>2007-12-28</annee><preview>https://p.scdn.co/mp3-preview/38ad3c7dd6fb9eeb72e12480748b792d78d39ef2</preview></item><item><image>https://i.scdn.co/image/80bae2c539d320fb81c196e443cedb5c05875585</image><track>三人遊</track><artiste>方大同</artiste><album>橙月</album><annee>2008-12-19</annee><preview>https://p.scdn.co/mp3-preview/936740159e7fc616ca6739379825b4a285547c10</preview></item><item><image>https://i.scdn.co/image/03bc0ce773c7ac0f8785cc646261e75ae9ec87a4</image><track>紅豆</track><artiste>方大同</artiste><album>Timeless</album><annee>2009-08-11</annee><preview>https://p.scdn.co/mp3-preview/987dfb3f6a3b1204276e95fd5271cd65204e2880</preview></item><item><image>https://i.scdn.co/image/7d7b78e1624f85311a6424296eb8dfce0cbb81c2</image><track>Love Song</track><artiste>方大同</artiste><album>未來</album><annee>2007-12-28</annee><preview>https://p.scdn.co/mp3-preview/38ad3c7dd6fb9eeb72e12480748b792d78d39ef2</preview></item><item><image>https://i.scdn.co/image/80bae2c539d320fb81c196e443cedb5c05875585</image><track>三人遊</track><artiste>方大同</artiste><album>橙月</album><annee>2008-12-19</annee><preview>https://p.scdn.co/mp3-preview/936740159e7fc616ca6739379825b4a285547c10</preview></item><item><image>https://i.scdn.co/image/03bc0ce773c7ac0f8785cc646261e75ae9ec87a4</image><track>紅豆</track><artiste>方大同</artiste><album>Timeless</album><annee>2009-08-11</annee><preview>https://p.scdn.co/mp3-preview/987dfb3f6a3b1204276e95fd5271cd65204e2880</preview></item></playlist>
